source 'http://rubygems.org'

gem "middleman", "~><%= Middleman::VERSION %>"
gem "middleman-autoprefixer", ">= 2.4.3"
gem "slim", ">= 2.0"
gem "bourbon", ">= 4.2.0"
gem "neat", ">= 1.7.1"

gem "middleman-livereload"
gem "middleman-deploy"