source 'http://rubygems.org'

gem "middleman", "~><%= Middleman::VERSION %>"
gem "middleman-autoprefixer", "~> 0.2.3"
gem "middleman-deploy", '~> 0.3.0'
gem "middleman-livereload", "~> 3.1.0"
gem "slim", "~> 2.0"